---
title: "615 assignment 3 data cleaning"
author: "Si Chen"
date: "September 30, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,dev="CairoPNG",fig.align = "center", 
                      fig.width = 5.656, fig.height = 4, global.par = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60),  # For code
                      width = 60)  # For output
options(cli.width = 60)  # For tidyverse loading messages
#install.packages("pacman",repos="https://cloud.r-project.org")
pacman::p_load("ggplot2","knitr","arm","foreign","car","Cairo","data.table","dplyr")
par (mar=c(3,3,2,1), mgp=c(2,.7,0), tck=-.01)
```

```{r }
#import datasets from MEASURESOFBIRTHANDDEATH and RISKFACTORSANDACCESSTOCARE
tableM <- read.csv("MEASURESOFBIRTHANDDEATH.csv")
tableR <- read.csv("RISKFACTORSANDACCESSTOCARE.csv")

# select the variable total death in RISKFACTORSANDACCESSTOCARE
death <- select(tableM, Total_Deaths)

# select the variable obesity, smoker, diabetes, uninsured, Dentist_Rate,CHSI_State_Name from RISKFACTORSANDACCESSTOCARE
risk <- select(tableR,Obesity,Smoker,Diabetes,Uninsured,Dentist_Rate,CHSI_State_Name)

# combine to a new table
tablenew <- cbind.data.frame(death,risk)

# remove all useless inputs
tablenew[tablenew < 0] <- NA

# create the final data frame
tablenew1<-tablenew[complete.cases(tablenew),]


```



```{r }
library(ggplot2)


ggplot(tablenew1) + geom_point(aes(x = Obesity, y = Total_Deaths, color = Obesity)) + geom_smooth(aes(x = Obesity, y = Total_Deaths)) + ggtitle( "SiChen： Obesity vs Death")



```


```{r}
table.state <- tablenew1 %>% group_by(CHSI_State_Name) %>% summarise(totaldeath = sum(Total_Deaths),uninsured=sum(Uninsured))

ggplot(table.state)+
  ggtitle("siwei: uninsured VS total_death")+
  geom_point(mapping = aes(x = uninsured,y = totaldeath))+
  geom_smooth(mapping = aes(x = uninsured,y = totaldeath))

```

```{r}
#plot smoker with death

ggplot(data = tablenew1) + 
  geom_point(mapping = aes(x = Smoker, y = Total_Deaths))+ geom_smooth(mapping = aes(x = Smoker, y = Total_Deaths)) + ggtitle( "Mark： Smoker vs Death")
```


```{r}
#plot diabetes with death
ggplot(data = tablenew1,mapping = aes(x = Diabetes, y = Total_Deaths)) + 
  geom_point()+ geom_smooth(method = "gam",formula = y~s(x,bs="cs"))+
  ggtitle("Grace: Diabetes VS total_death")

```