---
title: "risk factors and access to care"
author: "Siwei Hu"
date: "September 30, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,dev="CairoPNG",fig.align = "center", 
                      fig.width = 5.656, fig.height = 4, global.par = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60),  # For code
                      width = 60)  # For output
options(cli.width = 60)  # For tidyverse loading messages
#install.packages("pacman",repos="https://cloud.r-project.org")
pacman::p_load("ggplot2","knitr","arm","foreign","car","Cairo","data.table","dplyr")
par (mar=c(3,3,2,1), mgp=c(2,.7,0), tck=-.01)
```



```{r}
library(readr)
risk <- read_csv("RISKFACTORSANDACCESSTOCARE.csv")
bnd<- read_csv("MEASURESOFBIRTHANDDEATH.csv")
```



```{r}
bnd.d <- select(bnd, Total_Deaths)
risk <- select(risk,Obesity,Smoker,Diabetes,Uninsured,Dentist_Rate,CHSI_State_Name)
table.new[table.new < 0] <- NA
table.new1<-table.new[complete.cases(table.new),]
```
